# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:

    # using tox
    toxify:

        docker:
            - image: circleci/python:3.7

        steps:
            - checkout
            # download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: pip install tox && tox

workflows:
    version: 2

    cvdata:
        jobs:
        - toxify

#jobs:
#  build:
#    docker:
#      # specify the version you desire here
#      # CircleCI maintains a library of pre-built images
#      # documented at https://circleci.com/docs/2.0/circleci-images/
#      - image: circleci/python:3.7
#
#    working_directory: ~/repo
#
#    steps:
#      - checkout
#
#      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "requirements.txt" }}
#            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-
#
#      - run:
#          name: install dependencies
#          command: |
#            python3 -m venv venv
#            . venv/bin/activate
#            pip install -e .
#            pip install tox
#
#      - save_cache:
#          paths:
#            - ./venv
#          key: v1-dependencies-{{ checksum "requirements.txt" }}
#
#      # run tests with tox
#      - run:
#          name: run tests
#          command: |
#            . venv/bin/activate
#            tox
#
#      - store_artifacts:
#          path: test-reports
#          destination: test-reports
